# baseURL = "http://example.org/"
baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Aspose Total"



# enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["lutsk-aspose-theme"]


# Google Tag Manager settings
[params.gtm]
aspose_id = "GTM-NJMHSH"
cloud_id = "GTM-TSXP9CZ"
conholdate_id = "GTM-N4D44QW"
products_app_id = "UA-3109235-5"